# Generated by Django 3.2.5 on 2021-08-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perawatan', '0005_auto_20210713_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=500)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diubah', models.DateTimeField(auto_now=True)),
                ('fasilitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perawatan.fasilitas')),
            ],
            options={
                'verbose_name_plural': 'Pengujian',
                'ordering': ['-dibuat'],
            },
        ),
        migrations.CreateModel(
            name='PaketPengujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=500)),
                ('persentase', models.FloatField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diubah', models.DateTimeField(auto_now=True)),
                ('pengujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengujian.pengujian')),
            ],
            options={
                'verbose_name_plural': 'Paket Pengujian',
                'ordering': ['-dibuat'],
            },
        ),
        migrations.AddIndex(
            model_name='pengujian',
            index=models.Index(fields=['nama'], name='pengujian_p_nama_86d99b_idx'),
        ),
        migrations.AddIndex(
            model_name='paketpengujian',
            index=models.Index(fields=['nama'], name='pengujian_p_nama_c48db7_idx'),
        ),
    ]
