# Generated by Django 3.2.5 on 2021-08-26 13:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pengujian', '0003_pengujian_berakhir'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengujian',
            name='pemilik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengujian',
            name='berakhir',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 13, 6, 30, 335499, tzinfo=utc)),
        ),
    ]
