# Generated by Django 3.2.5 on 2021-08-29 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pengujian', '0004_auto_20210826_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paketpengujian',
            options={'ordering': ['dibuat'], 'verbose_name_plural': 'Paket Pengujian'},
        ),
        migrations.AlterField(
            model_name='pengujian',
            name='berakhir',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 8, 6, 38, 994772, tzinfo=utc)),
        ),
    ]
