# Generated by Django 3.2.5 on 2021-08-30 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pengujian', '0005_auto_20210829_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengujian',
            name='berakhir',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 3, 38, 52, 695352, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pengujian',
            name='dibuat',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 3, 38, 52, 695352, tzinfo=utc)),
        ),
    ]
