# Generated by Django 3.2.5 on 2021-10-05 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pengujian', '0006_auto_20210830_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengujian',
            name='berakhir',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 2, 26, 2, 764592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pengujian',
            name='dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
