# Generated by Django 3.2.5 on 2021-08-05 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('spek', models.TextField(blank=True, verbose_name='spesifikasi')),
                ('jumlah', models.IntegerField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Barang',
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lokasi',
            },
        ),
        migrations.AddIndex(
            model_name='lokasi',
            index=models.Index(fields=['nama'], name='stok_lokasi_nama_e9fd45_idx'),
        ),
        migrations.AddField(
            model_name='barang',
            name='lokasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.lokasi'),
        ),
        migrations.AddIndex(
            model_name='barang',
            index=models.Index(fields=['nama', 'lokasi'], name='stok_barang_nama_eafd33_idx'),
        ),
    ]
