# Generated by Django 3.2.5 on 2021-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_auto_20210805_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media/barang'),
        ),
    ]
