# Generated by Django 3.2.5 on 2021-08-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0004_auto_20210805_1739'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='barang',
            name='stok_barang_nama_eafd33_idx',
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stok.kategori'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='barang',
            index=models.Index(fields=['nama', 'lokasi', 'kategori'], name='stok_barang_nama_20bb95_idx'),
        ),
    ]
