# Generated by Django 3.2.5 on 2021-08-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0007_auto_20210805_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='dikembalikan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
