# Generated by Django 3.2.5 on 2021-08-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0008_alter_pinjam_dikembalikan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinjam',
            options={'ordering': ['-kapan'], 'verbose_name_plural': 'Pinjam'},
        ),
    ]
