# Generated by Django 3.2.5 on 2021-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0009_alter_pinjam_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='foto',
            field=models.ImageField(blank=True, upload_to='barang'),
        ),
    ]
