# Generated by Django 3.2.5 on 2021-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0010_alter_barang_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='bmn',
            field=models.TextField(blank=True),
        ),
    ]
