# Generated by Django 3.2.5 on 2021-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Keahlian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diubah', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Keahlian',
                'ordering': ['nama'],
            },
        ),
    ]
