# Generated by Django 3.2.5 on 2021-07-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perawatan', '0002_fasilitas_keahlian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasilitas',
            name='nama',
            field=models.CharField(max_length=500),
        ),
    ]
