name: Deploy Aerotron

on:
  push:
    tags:
      - '*'

jobs:
  deploy_aerotron_ui:
    name: Deploy Aerotron UI
    runs-on: server-17
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Check and Install Dependencies
        run: |
          cd templates/tronbase
          node -v
          npm -v
          npm install
          npm install -g @quasar/cli

      - name: Build UI
        run: |
          cd templates/tronbase
          cat > .env << ENDOFFILE
          STREAM_ADDRESS=${{ secrets.STREAM_ADDRESS }}
          PAGE_SIZE=10
          REST_HOST=aerowork.bppt.go.id
          ENDOFFILE
          quasar build

      - name: Cleaning Up
        run: |
          rm -rf aerotron oten perawatan stok LICENSE manage.py README.md requirements.txt
          cd templates/tronbase
          rm -rf node_modules public src
          rm -rf babel.config.js firebase.json jsconfig.json package.json package-lock.json
          rm -rf quasar.conf.js README.md
          mv dist/spa/* ../..
          cd ../..
          rm -rf templates

  deploy_aerotron_core:
    name: Deploy Aerotron Core
    runs-on: server-19
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Create Environment
        run: |
          cat > .env << ENDOFFILE
          STREAM_ADDRESS=${{ secrets.STREAM_ADDRESS }}
          DEBUG=prod
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          STATIC_ROOT=${{ secrets.STATIC_ROOT }}
          PAGE_SIZE=10
          ENDOFFILE

      - name: Install Requirements
        run: |
          pip install -r requirements.txt
          python3 manage.py migrate

      - name: Cleaning Up
        run: |
          rm -rf templates/tronbase
