name: Deploy Aerotron

on:
  push:
    tags:
      - '*'

jobs:
  deploy_aerotron:
    name: Deploy Aerotron UI
    runs-on: server-17
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Check and Install Dependencies
        run: |
          cd templates/tronbase
          node -v
          npm -v
          npm install
          npm install -g @quasar/cli

      - name: Build UI
        run: |
          cd templates/tronbase
          cat > .env << ENDOFFILE
          STREAM_ADDRESS=${{ secrets.STREAM_ADDRESS }}
          PAGE_SIZE=10
          REST_HOST=aerowork.bppt.go.id
          ENDOFFILE
          quasar build

      - name: Cleaning Up
        run: |
          rm -rf aerotron oten perawatan stok
          cd templates/tronbase
          rm -rf node_modules public src
          rm -rf babel.config.js firebase.json jsconfig.json package.json package-lock.json
          rm -rf quasar.conf.js README.md
          mv dist/spa/* ../..
