name: Deploy Aerotron

on:
  push:
    tags:
      - '*'

jobs:
  upload_aerobro:
    name: Upload Aplikasi Aerobro
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Init Directory
        run: |
          mkdir aerotron

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Check and Install Dependencies
        run: |
          cd ui
          node -v
          npm -v
          npm install
          npm install -g @quasar/cli

      - name: Build UI
        run: |
          mkdir aerotron/spa
          cd ui
          cat > .env << ENDOFFILE
          STREAM_ADDRESS=${{ secrets.STREAM_ADDRESS }}
          ACC_THRESHOLD_MIN=0.3
          ACC_THRESHOLD_MAX=0.7
          STRAIN_THRESHOLD_MIN=0.4
          STRAIN_THRESHOLD_MAX=0.6
          DISP_THRESHOLD_MIN=0.4
          DISP_THRESHOLD_MAX=0.6
          REPO_NAME=aerotron
          ENDOFFILE
          quasar build
          cp -r dist/spa/* ../aerotron

      - name: Make Build Main Env.
        run: |
          cat > .env << ENDOFFILE
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          ENDOFFILE
