name: Deploy Aerotron

on:
  push:
    tags:
      - '*'

jobs:
  upload_aerobro:
    name: Upload Aplikasi Aerobro
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Init Directory
        run: |
          mkdir aerobro

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Check and Install Dependencies
        run: |
          cd ui
          node -v
          npm -v
          npm install
          npm install -g @quasar/cli

      - name: Build UI
        run: |
          mkdir aerotron/spa
          cd ui
          cat > .env << ENDOFFILE
          STREAM_ADDRESS=${{ secrets.STREAM_ADDRESS }}
          ACC_THRESHOLD_MIN=0.3
          ACC_THRESHOLD_MAX=0.7
          STRAIN_THRESHOLD_MIN=0.4
          STRAIN_THRESHOLD_MAX=0.6
          DISP_THRESHOLD_MIN=0.4
          DISP_THRESHOLD_MAX=0.6
          REPO_NAME=aerotron
          ENDOFFILE
          quasar build
          cp -r dist/spa/* ../aerotron

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Make Build Main Env.
        run: |
          cat > .env << ENDOFFILE
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          ENDOFFILE

      - name: Build Worker Using Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move to aerotron Directory
        run: |
          mv target/release/aerotron aerotron/
          mv proc/ aerotron/
          ls aerotron/

  deploy_aerotron_ui:
    name: Deploy aerotron UI
    needs: upload_aerotron
    runs-on: ubuntu-20.04
    steps:
      - name: Make Main Env.
        run: |
          cat > aerotron/.env << ENDOFFILE
          MQTT_ADDR=${{ secrets.MQTT_ADDR }}
          MQTT_USER=${{ secrets.MQTT_USER }}
          MQTT_PWD=${{ secrets.MQTT_PWD }}
          MSG_TOPIC=${{ secrets.MSG_TOPIC }}
          APP_PORT=3000
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          ENDOFFILE

      - name: Make Proc. Env.
        run: |
          cat > aerotron/proc/.env << ENDOFFILE
          STREAM_ADDRESS=${{ secrets.WS_ADDRESS }}
          ACC_THRESHOLD_MIN=0.4
          ACC_THRESHOLD_MAX=0.7
          STRAIN_THRESHOLD_MIN=0.4
          STRAIN_THRESHOLD_MAX=0.7
          DISP_THRESHOLD_MIN=3.0
          DISP_THRESHOLD_MAX=3.5
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          ENDOFFILE

      - name: Cleaning Up
        run: |
          rm Cargo.lock Cargo.toml
          rm -rf src target ui
          mv aerotron/ aerotrons/
          mv aerotrons/* .
          rm -rf aerotrons/
